import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const clean=(s:string)=>s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const tokens=(s:string)=>new Set(clean(s).split(" ").filter(x=>x.length>1));
function jaccard(a:string,b:string){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let i=0;for(const x of A)if(B.has(x))i++;return i/(A.size+B.size-i)}
function scoreMatch(title:string,artist:string,c:any){const ct=String(c.title||""),ca=String(c.user?.username||c.publisher_metadata?.artist||c.metadata_artist||"");const t=jaccard(title,ct),a=jaccard(artist,ca);let s=t*.68+a*.32;if(clean(ct).includes(clean(title))||clean(title).includes(clean(ct)))s+=.08;if(clean(ca).includes(clean(artist))||clean(artist).includes(clean(ca)))s+=.08;return Math.max(0,Math.min(1,s))}
async function getToken(){const id=Deno.env.get("SOUNDCLOUD_CLIENT_ID"),sec=Deno.env.get("SOUNDCLOUD_CLIENT_SECRET");if(!id||!sec)throw new Error("SOUNDCLOUD_NOT_CONFIGURED");const basic=btoa(`${id}:${sec}`);const r=await fetch("https://secure.soundcloud.com/oauth/token",{method:"POST",headers:{"accept":"application/json","content-type":"application/x-www-form-urlencoded","authorization":`Basic ${basic}`},body:"grant_type=client_credentials"});if(!r.ok)throw new Error(`SOUNDCLOUD_AUTH_${r.status}`);return (await r.json()).access_token}
async function searchTrack(q:string,token:string){const u=new URL("https://api.soundcloud.com/tracks");u.searchParams.set("q",q);u.searchParams.set("access","playable");u.searchParams.set("limit","10");u.searchParams.set("linked_partitioning","true");const r=await fetch(u,{headers:{"accept":"application/json","authorization":`OAuth ${token}`}});if(!r.ok)throw new Error(`SOUNDCLOUD_SEARCH_${r.status}`);const d=await r.json();return Array.isArray(d.collection)?d.collection:[]}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const body=await req.json().catch(()=>({}));const category=body.category?String(body.category):null;const limit=Math.max(1,Math.min(Number(body.limit||20),50));const threshold=Math.max(.5,Math.min(Number(body.threshold||.78),.98));const url=Deno.env.get("SUPABASE_URL")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(url,service);const token=await getToken();let q=db.from("vt_provider_matches").select("id,catalog_id,vt_catalog!inner(id,title,artist,category,active)").eq("provider","soundcloud").eq("match_status","pending").eq("vt_catalog.active",true).limit(limit);if(category)q=q.eq("vt_catalog.category",category);const {data:rows,error}=await q;if(error)throw error;let accepted=0,rejected=0;const results=[];for(const row of rows||[]){const song=(row as any).vt_catalog;const query=`${song.artist||""} ${song.title||""}`.trim();let best:any=null,bestScore=0;try{for(const c of await searchTrack(query,token)){const s=scoreMatch(song.title||"",song.artist||"",c);if(s>bestScore){bestScore=s;best=c}}}catch(e){results.push({catalog_id:song.id,error:String(e)});continue}const status=best&&bestScore>=threshold?"accepted":"rejected";if(status==="accepted")accepted++;else rejected++;const payload:any={provider_track_id:best?String(best.id||best.urn||""):null,provider_url:best?.permalink_url||null,provider_title:best?.title||null,provider_artist:best?.user?.username||best?.publisher_metadata?.artist||best?.metadata_artist||null,artwork_url:best?.artwork_url||null,duration_ms:best?.duration||null,access_status:best?.access||null,match_score:Number(bestScore.toFixed(4)),match_status:status,checked_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error:ue}=await db.from("vt_provider_matches").update(payload).eq("id",(row as any).id);if(ue)throw ue;results.push({catalog_id:song.id,title:song.title,artist:song.artist,status,score:bestScore,provider_title:payload.provider_title,provider_artist:payload.provider_artist,provider_url:payload.provider_url})}
return new Response(JSON.stringify({ok:true,category,processed:(rows||[]).length,accepted,rejected,threshold,results}),{headers:{...cors,"content-type":"application/json"}})}catch(e){const msg=String(e);const status=msg.includes("SOUNDCLOUD_NOT_CONFIGURED")?503:500;return new Response(JSON.stringify({ok:false,error:msg,needsSoundCloudCredentials:msg.includes("SOUNDCLOUD_NOT_CONFIGURED")}),{status,headers:{...cors,"content-type":"application/json"}})}});